export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODECT_LIST_SUCCESS = 'PRODECT_LIST_SUCCESS'
export const PRODECT_LIST_FAIL = 'PRODECT_LIST_FAIL'

export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'
export const FILTER_PRODUCT = 'FILTER_PRODUCT'
export const PRICE_FILTER_PRODUCT = 'PRICE_FILTER_PRODUCT'